"""empty message

Revision ID: 31101f81fbdf
Revises: aa7163329d49
Create Date: 2021-10-07 11:00:32.007162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31101f81fbdf'
down_revision = 'aa7163329d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lumber_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('prototype_prefix', sa.String(), nullable=True),
    sa.Column('prototype_suffix', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('budget_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_total', sa.Integer(), nullable=True),
    sa.Column('panels_onsite_date', sa.Date(), nullable=True),
    sa.Column('sales_order_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('lumber_prices')
    # ### end Alembic commands ###
