"""empty message

Revision ID: 35fc25529560
Revises: 31101f81fbdf
Create Date: 2021-10-07 11:07:34.477757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fc25529560'
down_revision = '31101f81fbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('panel_vendor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'panel_vendor')
    # ### end Alembic commands ###
