"""empty message

Revision ID: 4f65a76afd10
Revises: b39a444e0b43
Create Date: 2021-11-04 17:47:06.803588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f65a76afd10'
down_revision = 'b39a444e0b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('wall_panels_cost_per_elev_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'wall_panels_cost_per_elev_sqft')
    # ### end Alembic commands ###
