"""empty message

Revision ID: 722070bd3de8
Revises: 9211b3de7419
Create Date: 2021-09-30 09:55:22.737733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '722070bd3de8'
down_revision = '9211b3de7419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodities', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('commodities', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('commodities', sa.Column('close', sa.Float(), nullable=True))
    op.add_column('commodities', sa.Column('change', sa.Float(), nullable=True))
    op.drop_column('commodities', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodities', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('commodities', 'change')
    op.drop_column('commodities', 'close')
    op.drop_column('commodities', 'open')
    op.drop_column('commodities', 'ticker')
    # ### end Alembic commands ###
