"""empty message

Revision ID: 80daa4746e25
Revises: b07c99bacd77
Create Date: 2021-10-15 13:31:36.736154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80daa4746e25'
down_revision = 'b07c99bacd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('wall_panels_cost', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('n_wall_panels_ext', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('n_wall_panels_int', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('sqft_wall_panels_ext', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('sqft_wall_panels_int', sa.Float(), nullable=True))
    op.drop_column('projects', 'buyout_structwood')
    op.drop_column('projects', 'budget_structwood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('budget_structwood', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('buyout_structwood', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'sqft_wall_panels_int')
    op.drop_column('projects', 'sqft_wall_panels_ext')
    op.drop_column('projects', 'n_wall_panels_int')
    op.drop_column('projects', 'n_wall_panels_ext')
    op.drop_column('projects', 'wall_panels_cost')
    # ### end Alembic commands ###
