"""empty message

Revision ID: 868ef683c07f
Revises: 
Create Date: 2021-09-21 17:07:07.255843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868ef683c07f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('budget_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_total', sa.Integer(), nullable=True),
    sa.Column('panels_onsite_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
