"""empty message

Revision ID: 9211b3de7419
Revises: 3d842f26d437
Create Date: 2021-09-29 17:38:26.507688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9211b3de7419'
down_revision = '3d842f26d437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Commodities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commodities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Commodities_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Commodities_pkey')
    )
    op.drop_table('commodities')
    # ### end Alembic commands ###
