"""empty message

Revision ID: a27a39c7021c
Revises: 722070bd3de8
Create Date: 2021-09-30 10:05:27.337467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a27a39c7021c'
down_revision = '722070bd3de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commodities')
    # ### end Alembic commands ###
