"""empty message

Revision ID: aa7163329d49
Revises: b3f61ef7dc1f
Create Date: 2021-10-06 11:22:33.067802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa7163329d49'
down_revision = 'b3f61ef7dc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('lumber_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lumber_prices',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date', name='lumber_prices_pkey')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sqft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prototype_prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prototype_suffix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('budget_structwood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyout_structwood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyout_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('panels_onsite_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sales_order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    # ### end Alembic commands ###
