"""empty message

Revision ID: b07c99bacd77
Revises: 35fc25529560
Create Date: 2021-10-07 11:28:44.562950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07c99bacd77'
down_revision = '35fc25529560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('prototype_prefix', sa.String(), nullable=True),
    sa.Column('prototype_suffix', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('budget_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_structwood', sa.Integer(), nullable=True),
    sa.Column('buyout_total', sa.Integer(), nullable=True),
    sa.Column('panels_onsite_date', sa.Date(), nullable=True),
    sa.Column('sales_order_date', sa.Date(), nullable=True),
    sa.Column('panel_vendor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
