"""empty message

Revision ID: b3f61ef7dc1f
Revises: a27a39c7021c
Create Date: 2021-09-30 16:12:35.549623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f61ef7dc1f'
down_revision = 'a27a39c7021c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lumber_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lumber_prices')
    # ### end Alembic commands ###
